"""
Audit report for a single agent.ask() call.

Renders an AgentResult into a self-contained HTML page: the question, the exact
summary sent to the model, each attempt (blocked ones and why), the final code
and answer, data-quality warnings, withheld PII columns, and the token saving.
This is the "what left my machine and what did the guardrail do" trail that makes
the library defensible for company use.
"""

import html as _html


def _esc(x) -> str:
    return _html.escape(str(x))


def _section(title, inner):
    return f'<section><h2>{_esc(title)}</h2>{inner}</section>'


def _pre(text):
    return f'<pre>{_esc(text)}</pre>' if text else '<p class="muted">(none)</p>'


def build_audit_html(result) -> str:
    r = result
    status = ("BLOCKED" if r.blocked else "OK")
    status_cls = "bad" if r.blocked else "ok"

    # attempts (prefer the richer trace; fall back to the bare code list)
    trace = r.trace or [{"code": c, "blocked": None, "reason": None}
                        for c in (r.attempts or [])]
    attempts_html = []
    for i, t in enumerate(trace, 1):
        if t.get("blocked"):
            badge = '<span class="badge bad">blocked</span>'
            reason = f'<p class="reason">{_esc(t.get("reason"))}</p>'
        elif t.get("blocked") is False:
            badge = '<span class="badge ok">ran</span>'
            reason = ""
        else:
            badge = '<span class="badge">attempt</span>'
            reason = ""
        attempts_html.append(
            f'<div class="attempt"><h3>Attempt {i} {badge}</h3>'
            f'{_pre(t.get("code"))}{reason}</div>')
    attempts_block = "".join(attempts_html) or '<p class="muted">(none)</p>'

    # data-quality issues
    if r.issues:
        rows = "".join(
            f'<tr><td>{_esc(i.get("rule_id"))}</td>'
            f'<td>{_esc(i.get("severity"))}</td>'
            f'<td>{_esc(i.get("column"))}</td>'
            f'<td>{_esc(i.get("message"))}</td></tr>'
            for i in r.issues)
        issues_html = (
            '<table><thead><tr><th>rule</th><th>severity</th><th>column</th>'
            f'<th>message</th></tr></thead><tbody>{rows}</tbody></table>')
    else:
        issues_html = '<p class="muted">No data-quality issues detected.</p>'

    # PII withheld
    pii = r.pii_columns or []
    pii_html = (f'<p><strong>{len(pii)}</strong> column(s) flagged as PII: '
                f'{_esc(", ".join(pii))}</p>' if pii
                else '<p class="muted">No PII columns detected.</p>')

    # tokens
    tk = r.tokens or {}
    if tk:
        tokens_html = (
            f'<p>Summary sent: <strong>{_esc(tk.get("summary_tokens"))}</strong> '
            f'tokens vs raw data ~<strong>{_esc(tk.get("raw_tokens"))}</strong> '
            f'(saved ~{_esc(tk.get("saved_percent"))}%).</p>')
    else:
        tokens_html = '<p class="muted">(no token estimate)</p>'

    answer_html = (f'<p class="reason">{_esc(r.reason)}</p>' if r.blocked
                   else _pre(repr(r.answer)))

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>safedata audit report</title>
<style>
  body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
         max-width: 920px; margin: 2rem auto; padding: 0 1rem; color: #1b1f24; }}
  h1 {{ margin-bottom: .2rem; }}
  h2 {{ border-bottom: 1px solid #e3e6ea; padding-bottom: .3rem; margin-top: 2rem; }}
  pre {{ background: #0d1117; color: #e6edf3; padding: .8rem 1rem; border-radius: 6px;
        overflow-x: auto; font-size: .85rem; white-space: pre-wrap; }}
  table {{ border-collapse: collapse; width: 100%; font-size: .9rem; }}
  th, td {{ border: 1px solid #e3e6ea; padding: .4rem .6rem; text-align: left;
           vertical-align: top; }}
  th {{ background: #f6f8fa; }}
  .muted {{ color: #6b7280; }}
  .reason {{ color: #b91c1c; }}
  .badge {{ font-size: .72rem; padding: .1rem .5rem; border-radius: 999px;
           background: #e5e7eb; }}
  .badge.ok {{ background: #dcfce7; color: #166534; }}
  .badge.bad {{ background: #fee2e2; color: #991b1b; }}
  .status.ok {{ color: #166534; }} .status.bad {{ color: #991b1b; }}
  .attempt {{ margin-bottom: 1rem; }}
</style></head>
<body>
  <h1>safedata audit report</h1>
  <p>Status: <strong class="status {status_cls}">{status}</strong>
     &middot; {len(trace)} attempt(s)</p>
  {_section("Question", _pre(r.question))}
  {_section("Summary sent to the model (raw rows withheld)", _pre(r.summary))}
  {_section("Attempts", attempts_block)}
  {_section("Final answer", answer_html)}
  {_section("Data-quality warnings", issues_html)}
  {_section("PII withheld", pii_html)}
  {_section("Token saving", tokens_html)}
  <p class="muted" style="margin-top:2rem">Generated by safedata-guard. Heuristic,
     best-effort; not a compliance guarantee.</p>
</body></html>"""
